# Generated by Django 5.2.4 on 2025-08-13 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
        ('principal', '0004_clase2'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindusers',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.clase2'),
        ),
        migrations.AddField(
            model_name='kindusers',
            name='tutor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kindusers',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
