# Generated by Django 5.2.4 on 2025-08-13 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_kindusers_clase_kindusers_tutor_alter_kindusers_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kindusers',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='kindusers',
            name='tutor',
        ),
    ]
