# Generated by Django 5.0.6 on 2025-08-09 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Alumno')),
                ('tutor', models.CharField(max_length=100, verbose_name='Nombre del Tutor')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero de Teléfono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.clase', verbose_name='Clase Inscrita')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['-created_at'],
            },
        ),
    ]
