# Generated by Django 5.0.6 on 2025-08-09 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alumnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título de la Tarea')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Tarea')),
                ('fecha_entrega', models.DateTimeField(verbose_name='Fecha de Entrega')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.clase', verbose_name='Clase Asociada')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-created_at'],
            },
        ),
    ]
