# Generated by Django 5.2.4 on 2025-08-13 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
        ('principal', '0003_tareas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumnos', models.ManyToManyField(blank=True, related_name='clases_inscritas', to='plataforma.kindusers', verbose_name='Alumnos Inscritos')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_impartidas', to=settings.AUTH_USER_MODEL, verbose_name='Profesor Asignado')),
            ],
        ),
    ]
