# Generated by Django 5.2.4 on 2025-08-17 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_clase2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.clase2', verbose_name='Clase Asociada'),
        ),
    ]
