# Generated by Django 5.2.4 on 2025-08-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_tareas_clase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Alumnos',
        ),
        migrations.DeleteModel(
            name='Clase',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
