# Generated by Django 5.2.4 on 2025-08-17 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_remove_kindusers_clase_remove_kindusers_tutor'),
        ('principal', '0006_remove_clase_profesor_remove_profesor_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='entregas', verbose_name='Archivo de entrega')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario del alumno')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de entrega')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='plataforma.kindusers', verbose_name='Alumno')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='principal.tareas', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-fecha_entrega'],
                'unique_together': {('tarea', 'alumno')},
            },
        ),
    ]
