# Generated by Django 5.0.6 on 2025-08-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Calificación'),
        ),
    ]
